web:
  extends:
    file: daedalus.yml
    service: daedalus
  links:
    - redis
  environment:
    DAEDALUS_REDIS_DSN: redis://redis
  ports:
    - "8000:8000"
  command: python daedalus/app.py
worker:
  extends:
    file: daedalus.yml
    service: daedalus
  links:
    - redis
  environment:
    DAEDALUS_REDIS_DSN: redis://redis
  command: worker
redis:
  image: redis
